// generated by @better-cms/cli — do not edit
import { createCmsClient } from 'better-cms/sveltekit';
import type {
	ClientAuthApi,
	ClientCmsConfig,
	CollectionApi,
	SingletonApi,
} from 'better-cms/sveltekit';

export interface Posts {
	title: string;
	slug: string;
	excerpt?: string;
	body?: unknown;
	cover?: {
		key: string;
		url: string;
		mime?: string;
		size?: number;
		width?: number;
		height?: number;
		alt?: string;
	};
	published?: boolean;
	id?: string;
	createdAt?: string;
	updatedAt?: string;
}

export interface Settings {
	siteTitle: string;
	tagline?: string;
	id?: string;
	createdAt?: string;
	updatedAt?: string;
}

export interface Cms {
	posts: CollectionApi<Posts>;
	settings: SingletonApi<Settings>;
	auth: ClientAuthApi;
}

/** Schema slice safe to ship to the browser. Pass to <CmsAdmin config={cmsConfig} />. */
export const cmsConfig: ClientCmsConfig = {
	collections: {
		posts: {
			kind: 'collection',
			fields: {
				title: {
					kind: 'text',
					storage: 'column',
					columnType: 'text',
					scalarType: 'string',
					validation: { required: true, max: 120 },
					editor: { component: 'TextField', props: { multiline: false } },
				},
				slug: {
					kind: 'slug',
					storage: 'column',
					columnType: 'text',
					scalarType: 'string',
					unique: true,
					indexed: true,
					validation: { required: true, max: 200, pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' },
					editor: { component: 'SlugField', props: { from: 'title' } },
				},
				excerpt: {
					kind: 'text',
					storage: 'column',
					columnType: 'text',
					scalarType: 'string',
					validation: { max: 500 },
					editor: { component: 'TextField', props: { multiline: true } },
				},
				body: {
					kind: 'richText',
					storage: 'json',
					columnType: 'text',
					validation: {},
					editor: { component: 'RichTextField', props: { impl: 'tiptap' } },
					llm: {
						describe:
							'Rich text content stored as a structured document (ProseMirror/Tiptap-compatible JSON).',
					},
				},
				cover: {
					kind: 'image',
					storage: 'json',
					columnType: 'text',
					validation: {},
					editor: {
						component: 'ImageField',
						props: { formats: ['jpg', 'png', 'webp'], maxSizeMB: 10 },
					},
					llm: {
						describe: 'Reference to an uploaded image. Stored as { key, url, alt, width, height }.',
					},
				},
				published: {
					kind: 'boolean',
					storage: 'column',
					columnType: 'integer',
					scalarType: 'boolean',
					defaultValue: false,
					validation: {},
					editor: { component: 'BooleanField' },
				},
				id: { kind: 'text', storage: 'column', columnType: 'text' },
				createdAt: { kind: 'date', storage: 'column', columnType: 'integer' },
				updatedAt: { kind: 'date', storage: 'column', columnType: 'integer' },
			},
			timestamps: true,
		},
		settings: {
			kind: 'singleton',
			fields: {
				siteTitle: {
					kind: 'text',
					storage: 'column',
					columnType: 'text',
					scalarType: 'string',
					validation: { required: true },
					editor: { component: 'TextField', props: { multiline: false } },
				},
				tagline: {
					kind: 'text',
					storage: 'column',
					columnType: 'text',
					scalarType: 'string',
					validation: {},
					editor: { component: 'TextField', props: { multiline: false } },
				},
				id: { kind: 'text', storage: 'column', columnType: 'text' },
				createdAt: { kind: 'date', storage: 'column', columnType: 'integer' },
				updatedAt: { kind: 'date', storage: 'column', columnType: 'integer' },
			},
			timestamps: true,
		},
	},
	basePath: '/api/cms',
};

export const cmsClient: Cms = createCmsClient(cmsConfig as never) as unknown as Cms;
