import type { CmsConfig, CollectionDef, FieldDef, SchemaIR } from '@better-cms/core';
import { pascalCase, tsFields } from './ts-emit.js';

/**
 * Emit a server-free client module. Bakes a *minimal* schema slice (kind +
 * slug-field name) and basePath into the file so consumers can
 * `import { cmsClient } from '$lib/cmsClient'` with zero plumbing.
 *
 *   import { cmsClient } from '$lib/cmsClient';
 *   const user = $derived(cmsClient.auth.getUser());
 *   const post = $derived(cmsClient.posts.get(page.params.slug));
 *
 * For the admin route, also exports `cmsConfig` (full ClientCmsConfig) which
 * <CmsAdmin> needs for its editor UI. Regenerate after every schema change.
 */
export function generateClient(schema: SchemaIR, config: CmsConfig): string {
	const collections = schema.collections as Record<string, CollectionDef>;
	const basePath = (config.basePath ?? '/api/cms').replace(/\/$/, '');

	const interfaces: string[] = [];
	const cmsLines: string[] = [];
	const minimalEntries: string[] = [];
	const fullEntries: string[] = [];

	for (const [name, def] of Object.entries(collections)) {
		if (name.startsWith('cms_')) continue;
		const typeName = pascalCase(name);
		interfaces.push(`export interface ${typeName} {\n${tsFields(def, '\t')}\n}`);
		const apiKind =
			def.kind === 'singleton' ? `SingletonApi<${typeName}>` : `CollectionApi<${typeName}>`;
		cmsLines.push(`\t${name}: ${apiKind};`);
		const slug = slugFieldOf(def);
		const slugPart = slug ? `, slugField: ${JSON.stringify(slug)}` : '';
		minimalEntries.push(`\t\t${name}: { kind: ${JSON.stringify(def.kind)}${slugPart} } as never,`);
		fullEntries.push(`\t\t${name}: ${JSON.stringify(def)},`);
	}

	return `// generated by @better-cms/cli — do not edit
import { createCmsClient } from 'better-cms/sveltekit';
import type { ClientAuthApi, ClientCmsConfig, CollectionApi, SingletonApi } from 'better-cms/sveltekit';

${interfaces.join('\n\n')}

export interface Cms {
${cmsLines.join('\n')}
\tauth: ClientAuthApi;
}

/**
 * Full schema slice for the admin UI. Pass to <CmsAdmin config={cmsConfig} />.
 * The runtime client below uses a smaller slice — keeps editor metadata out
 * of pages that don't render the admin.
 */
export const cmsConfig: ClientCmsConfig = {
\tcollections: {
${fullEntries.join('\n')}
\t},
\tbasePath: ${JSON.stringify(basePath)},
};

const RUNTIME_CONFIG = {
\tcollections: {
${minimalEntries.join('\n')}
\t},
\tbasePath: ${JSON.stringify(basePath)},
};

export const cmsClient: Cms = createCmsClient(RUNTIME_CONFIG as never) as unknown as Cms;
`;
}

function slugFieldOf(def: CollectionDef): string | null {
	const fields = def.fields as Record<string, FieldDef>;
	for (const [name, fd] of Object.entries(fields)) {
		if (fd.kind === 'slug') return name;
	}
	return null;
}
