import type { CollectionDef, FieldDef, SchemaIR } from '@better-cms/core';
import { camelCase, pascalCase, tsFields } from './ts-emit.js';

/**
 * Emit a drizzle SQLite schema file from the IR. User then runs `bun drizzle-kit push`.
 */
export function generateDrizzleSchema(schema: SchemaIR): string {
	const imports = new Set<string>(['sqliteTable']);
	const tableBlocks: string[] = [];

	const collections = schema.collections as Record<string, CollectionDef>;
	for (const [name, def] of Object.entries(collections)) {
		const tn = def.tableName ?? name;
		const colLines: string[] = [];
		const fields = def.fields as Record<string, FieldDef>;
		for (const [field, fd] of Object.entries(fields)) {
			const fn = drizzleColumnFn(fd);
			imports.add(fn);
			const opts = drizzleColumnOpts(field, fd);
			let line = `\t\t${field}: ${fn}(${JSON.stringify(field)}${opts ? `, ${opts}` : ''})`;
			if (field === 'id') line += '.primaryKey()';
			if (fd.unique && field !== 'id') line += '.unique()';
			if (fd.required && field !== 'id') line += '.notNull()';
			colLines.push(`${line},`);
		}
		const block = `export const ${camelCase(tn)} = sqliteTable(${JSON.stringify(tn)}, (t) => ({\n${colLines.join('\n')}\n}));`;
		tableBlocks.push(block);
	}

	const importStr = `import { ${[...imports].sort().join(', ')} } from 'drizzle-orm/sqlite-core';`;
	return `// generated by @better-cms/cli — do not edit\n${importStr}\n\n${tableBlocks.join('\n\n')}\n`;
}

function drizzleColumnFn(field: FieldDef): string {
	switch (field.columnType) {
		case 'integer':
			return 'integer';
		case 'real':
			return 'real';
		case 'blob':
			return 'blob';
		default:
			return 'text';
	}
}

function drizzleColumnOpts(_name: string, field: FieldDef): string | null {
	if (field.scalarType === 'boolean') return `{ mode: 'boolean' }`;
	if (field.scalarType === 'date') return `{ mode: 'timestamp_ms' }`;
	if (field.kind === 'select' && field.options) {
		const en = field.options.map((v) => JSON.stringify(v)).join(', ');
		return `{ enum: [${en}] as const }`;
	}
	return null;
}

export function generateTypes(schema: SchemaIR): string {
	const blocks: string[] = [];
	const collections = schema.collections as Record<string, CollectionDef>;
	for (const [name, def] of Object.entries(collections)) {
		blocks.push(`export interface ${pascalCase(name)} {\n${tsFields(def, '\t')}\n}`);
	}
	return `// generated by @better-cms/cli — do not edit\n\n${blocks.join('\n\n')}\n`;
}
