import type { CollectionDef, FieldDef, SchemaIR } from '@better-cms/core';

/**
 * Emit a drizzle SQLite schema file from the IR. User then runs `bun drizzle-kit push`.
 */
export function generateDrizzleSchema(schema: SchemaIR): string {
	const imports = new Set<string>(['sqliteTable']);
	const tableBlocks: string[] = [];

	const collections = schema.collections as Record<string, CollectionDef>;
	for (const [name, def] of Object.entries(collections)) {
		const tn = def.tableName ?? name;
		const colLines: string[] = [];
		const fields = def.fields as Record<string, FieldDef>;
		for (const [field, fd] of Object.entries(fields)) {
			const fn = drizzleColumnFn(fd);
			imports.add(fn);
			const opts = drizzleColumnOpts(field, fd);
			let line = `\t\t${field}: ${fn}(${JSON.stringify(field)}${opts ? `, ${opts}` : ''})`;
			if (field === 'id') line += '.primaryKey()';
			if (fd.unique && field !== 'id') line += '.unique()';
			if (fd.validation?.required && field !== 'id') line += '.notNull()';
			colLines.push(`${line},`);
		}
		const block = `export const ${camelCase(tn)} = sqliteTable(${JSON.stringify(tn)}, (t) => ({\n${colLines.join('\n')}\n}));`;
		tableBlocks.push(block);
	}

	const importStr = `import { ${[...imports].sort().join(', ')} } from 'drizzle-orm/sqlite-core';`;
	return `// generated by @better-cms/cli — do not edit\n${importStr}\n\n${tableBlocks.join('\n\n')}\n`;
}

function drizzleColumnFn(field: FieldDef): string {
	switch (field.columnType) {
		case 'integer':
			return 'integer';
		case 'real':
			return 'real';
		case 'blob':
			return 'blob';
		default:
			return 'text';
	}
}

function drizzleColumnOpts(_name: string, field: FieldDef): string | null {
	if (field.scalarType === 'boolean')
		return `{ mode: 'boolean' }`;
	if (field.scalarType === 'date')
		return `{ mode: 'timestamp_ms' }`;
	if (field.kind === 'select' && field.validation?.enum) {
		const en = field.validation.enum.map((v) => JSON.stringify(v)).join(', ');
		return `{ enum: [${en}] as const }`;
	}
	return null;
}

function camelCase(s: string): string {
	return s.replace(/[_-](\w)/g, (_, c: string) => c.toUpperCase());
}

export function generateTypes(schema: SchemaIR): string {
	const blocks: string[] = [];
	const collections = schema.collections as Record<string, CollectionDef>;
	for (const [name, def] of Object.entries(collections)) {
		blocks.push(`export interface ${pascalCase(name)} {\n${tsFields(def, '\t')}\n}`);
	}
	return `// generated by @better-cms/cli — do not edit\n\n${blocks.join('\n\n')}\n`;
}

function tsFields(def: CollectionDef, indent: string): string {
	const lines: string[] = [];
	const fields = def.fields as Record<string, FieldDef>;
	for (const [field, fd] of Object.entries(fields)) {
		const optional = fd.validation?.required && field !== 'id' ? '' : '?';
		lines.push(`${indent}${field}${optional}: ${tsType(fd)};`);
	}
	return lines.join('\n');
}

function tsType(field: FieldDef): string {
	if (field.kind === 'array' && field.array)
		return `Array<${tsType(field.array.of)}>`;
	if (field.kind === 'object' && field.object) {
		const inner = Object.entries(field.object.fields)
			.map(([n, f]) => `${n}${f.validation?.required ? '' : '?'}: ${tsType(f)}`)
			.join('; ');
		return `{ ${inner} }`;
	}
	if (field.kind === 'image' || field.kind === 'file')
		return `{ key: string; url: string; mime?: string; size?: number; width?: number; height?: number; alt?: string }`;
	if (field.kind === 'richText') return 'unknown';
	if (field.kind === 'json') return 'unknown';
	if (field.kind === 'relation' && field.relation)
		return field.relation.many ? 'string[]' : 'string';
	if (field.kind === 'select' && field.validation?.enum)
		return field.validation.enum.map((v) => JSON.stringify(v)).join(' | ');
	switch (field.scalarType) {
		case 'boolean':
			return 'boolean';
		case 'integer':
		case 'number':
			return 'number';
		case 'date':
			return 'Date';
		default:
			return 'string';
	}
}

function pascalCase(s: string): string {
	return s.replace(/(^|[_-])(\w)/g, (_, _sep, c: string) => c.toUpperCase());
}
