import { dirname, relative } from 'node:path';
import { detectSlugField } from '@better-cms/core';
import type { CmsConfig, CollectionDef, SchemaIR } from '@better-cms/core';
import { pascalCase, tsFields } from './ts-emit.js';

export interface GenerateClientOpts {
	/**
	 * Absolute path of the user's server CMS config module. The generated client
	 * uses this to lift the `Ctx` (auth context) type via `import type` —
	 * type-only, erased pre-bundle, never ships server runtime to the browser.
	 */
	configPath?: string;
	/** Absolute output path of the generated `cmsClient.ts`. */
	outPath?: string;
}

/**
 * Emit a server-free client module. Bakes a *minimal* schema slice (kind +
 * slug-field name) and basePath into the file so consumers can
 * `import { cmsClient } from '$lib/cmsClient'` with zero plumbing.
 *
 *   import { cmsClient } from '$lib/cmsClient';
 *   const ctx = $derived(cmsClient.auth.context());
 *   const post = $derived(cmsClient.posts.get(page.params.slug));
 *
 * For the admin route, also exports `cmsConfig` (full ClientCmsConfig) which
 * <CmsAdmin> needs for its editor UI. Regenerate after every schema change.
 *
 * `Ctx` flows from the server config via a *type-only* import. TypeScript
 * erases it before Vite/Rollup; the browser bundle never imports server
 * code, just the type signature.
 */
export function generateClient(
	schema: SchemaIR,
	config: CmsConfig,
	opts: GenerateClientOpts = {},
): string {
	const collections = schema.collections as Record<string, CollectionDef>;
	const basePath = (config.basePath ?? '/api/cms').replace(/\/$/, '');

	const interfaces: string[] = [];
	const cmsLines: string[] = [];
	const minimalEntries: string[] = [];
	const fullEntries: string[] = [];

	for (const [name, def] of Object.entries(collections)) {
		if (name.startsWith('cms_')) continue;
		const typeName = pascalCase(name);
		interfaces.push(`export interface ${typeName} {\n${tsFields(def, '\t')}\n}`);
		const apiKind =
			def.kind === 'singleton' ? `SingletonApi<${typeName}>` : `CollectionApi<${typeName}>`;
		cmsLines.push(`\t${name}: ${apiKind};`);
		const slug = detectSlugField(def.fields);
		const slugPart = slug ? `, slugField: ${JSON.stringify(slug)}` : '';
		minimalEntries.push(`\t\t${name}: { kind: ${JSON.stringify(def.kind)}${slugPart} } as never,`);
		fullEntries.push(`\t\t${name}: ${JSON.stringify(def, stripRuntime)},`);
	}

	const ctxImport = ctxTypeImport(opts);

	return `// generated by @better-cms/cli — do not edit
import { createCmsClient } from 'better-cms/sveltekit';
import type { ClientAuthApi, ClientCmsConfig, CollectionApi, SingletonApi } from 'better-cms/sveltekit';
${ctxImport.importLine}

${interfaces.join('\n\n')}

${ctxImport.typeAlias}

export interface Cms {
${cmsLines.join('\n')}
\tauth: ClientAuthApi<Ctx>;
}

/**
 * Full schema slice for the admin UI. Pass to <CmsAdmin config={cmsConfig} />.
 * The runtime client below uses a smaller slice — keeps editor metadata out
 * of pages that don't render the admin.
 */
export const cmsConfig: ClientCmsConfig<Record<string, never>, Ctx> = {
\tcollections: {
${fullEntries.join('\n')}
\t},
\tbasePath: ${JSON.stringify(basePath)},
};

const RUNTIME_CONFIG = {
\tcollections: {
${minimalEntries.join('\n')}
\t},
\tbasePath: ${JSON.stringify(basePath)},
};

export const cmsClient: Cms = createCmsClient<typeof RUNTIME_CONFIG.collections, Ctx>(
\tRUNTIME_CONFIG as never,
) as unknown as Cms;
`;
}

/**
 * Build the `import type` line that lifts `Ctx` from the server config
 * (via the resolved auth.context's return type). Falls back to `unknown` when
 * we don't know the config path.
 */
function ctxTypeImport(opts: GenerateClientOpts): {
	importLine: string;
	typeAlias: string;
} {
	if (!opts.configPath || !opts.outPath) {
		return {
			importLine: '',
			typeAlias: 'type Ctx = unknown;',
		};
	}
	const fromDir = dirname(opts.outPath);
	let rel = relative(fromDir, opts.configPath).replaceAll('\\', '/');
	rel = rel.replace(/\.(ts|js|mts|mjs)$/, '');
	if (!rel.startsWith('.')) rel = `./${rel}`;
	const importLine = `import type { default as __ServerConfig } from ${JSON.stringify(rel)};`;
	const typeAlias = [
		'type CtxOf<T> = T extends { auth: { context: (req: Request) => infer R | Promise<infer R> } }',
		'\t? R',
		'\t: unknown;',
		'export type Ctx = CtxOf<typeof __ServerConfig>;',
	].join('\n');
	return { importLine, typeAlias };
}

/**
 * JSON.stringify replacer that strips runtime-only fields from CollectionDef
 * before baking it into the generated client. `validation`, `access`, and
 * `hooks` carry function references — non-serializable. `schemas` is a lazy
 * getter object — recreated server-side; client doesn't need it.
 */
function stripRuntime(key: string, value: unknown): unknown {
	if (key === 'validation' || key === 'schemas' || key === 'access' || key === 'hooks')
		return undefined;
	return value;
}

