import type { CmsConfig, CollectionDef, FieldDef, SchemaIR } from '@better-cms/core';

/**
 * Emit a server-free client module. Bakes the schema + basePath into the
 * file so consumers can `import { cms } from '$lib/cmsClient'` and use
 * it directly — no layout loader, no prop threading.
 *
 *   import { cmsClient } from '$lib/cmsClient';
 *   const user = $derived(cmsClient.auth.getUser());
 *   const post = $derived(cmsClient.posts.get(page.params.slug));
 *
 * Regenerate after every schema change (`bcms generate --target=client`).
 */
export function generateClient(schema: SchemaIR, config: CmsConfig): string {
	const collections = schema.collections as Record<string, CollectionDef>;
	const basePath = (config.basePath ?? '/api/cms').replace(/\/$/, '');

	const interfaces: string[] = [];
	const cmsLines: string[] = [];
	const schemaEntries: string[] = [];

	for (const [name, def] of Object.entries(collections)) {
		if (name.startsWith('cms_')) continue;
		const typeName = pascalCase(name);
		interfaces.push(`export interface ${typeName} {\n${tsFields(def, '\t')}\n}`);
		const apiKind =
			def.kind === 'singleton' ? `SingletonApi<${typeName}>` : `CollectionApi<${typeName}>`;
		cmsLines.push(`\t${name}: ${apiKind};`);
		schemaEntries.push(`\t\t${name}: ${JSON.stringify(def)},`);
	}

	return `// generated by @better-cms/cli — do not edit
import { createCmsClient } from 'better-cms/sveltekit';
import type { ClientAuthApi, ClientCmsConfig, CollectionApi, SingletonApi } from 'better-cms/sveltekit';

${interfaces.join('\n\n')}

export interface Cms {
${cmsLines.join('\n')}
\tauth: ClientAuthApi;
}

/** Schema slice safe to ship to the browser. Pass to <CmsAdmin config={cmsConfig} />. */
export const cmsConfig: ClientCmsConfig = {
\tcollections: {
${schemaEntries.join('\n')}
\t},
\tbasePath: ${JSON.stringify(basePath)},
};

export const cmsClient: Cms = createCmsClient(cmsConfig as never) as unknown as Cms;
`;
}

function tsFields(def: CollectionDef, indent: string): string {
	const lines: string[] = [];
	const fields = def.fields as Record<string, FieldDef>;
	for (const [field, fd] of Object.entries(fields)) {
		const optional = fd.validation?.required && field !== 'id' ? '' : '?';
		lines.push(`${indent}${field}${optional}: ${tsType(fd)};`);
	}
	return lines.join('\n');
}

function tsType(field: FieldDef): string {
	if (field.kind === 'array' && field.array) return `Array<${tsType(field.array.of)}>`;
	if (field.kind === 'object' && field.object) {
		const inner = Object.entries(field.object.fields)
			.map(([n, f]) => `${n}${f.validation?.required ? '' : '?'}: ${tsType(f)}`)
			.join('; ');
		return `{ ${inner} }`;
	}
	if (field.kind === 'image' || field.kind === 'file')
		return '{ key: string; url: string; mime?: string; size?: number; width?: number; height?: number; alt?: string }';
	if (field.kind === 'richText') return 'unknown';
	if (field.kind === 'json') return 'unknown';
	if (field.kind === 'relation' && field.relation)
		return field.relation.many ? 'string[]' : 'string';
	if (field.kind === 'select' && field.validation?.enum)
		return field.validation.enum.map((v) => JSON.stringify(v)).join(' | ');
	switch (field.scalarType) {
		case 'boolean':
			return 'boolean';
		case 'integer':
		case 'number':
			return 'number';
		case 'date':
			return 'Date';
		default:
			return 'string';
	}
}

function pascalCase(s: string): string {
	return s.replace(/(^|[_-])(\w)/g, (_, _sep, c: string) => c.toUpperCase());
}
